apiVersion: platform.chrishouse.io/v1alpha1
kind: AKSCluster
metadata:
  name: aks-app-spoke
  namespace: crossplane-system
spec:
  # Pin to specific composition revision to prevent automatic updates
  compositionUpdatePolicy: Manual
  compositionRevisionRef:
    name: xaksclusters.platform.chrishouse.io-ba6e116
  location: eastus
  resourceGroupName: rg-landing-zone-dev
  nodeCount: 2
  minNodeCount: 2
  maxNodeCount: 4
  enableAutoScaling: true
  vmSize: Standard_B2s
  priority: Regular
  kubernetesVersion: "1.32"
  subnetId: /subscriptions/f989de0f-8697-4a05-8c34-b82c941767c0/resourceGroups/rg-landing-zone-dev/providers/Microsoft.Network/virtualNetworks/vnet-spoke-dev/subnets/AksNodesSubnet
  serviceCidr: "10.101.0.0/16"
  dnsServiceIp: "10.101.0.10"
  serviceMeshEnabled: true
  serviceMeshInternalIngressEnabled: true
  serviceMeshExternalIngressEnabled: true
