---
apiVersion: v1
kind: Namespace
metadata:
  name: "xportalinfra-dev"
  labels:
    app.kubernetes.io/managed-by: crossplane
    app.kubernetes.io/name: xportalinfra
    app.kubernetes.io/instance: "xportalinfra-dev"
    armportal.chrishouse.io/blueprint: "xp-building-blocks"
    armportal.chrishouse.io/version: "2.0.0"
    armportal.chrishouse.io/request-id: "200"
    armportal.chrishouse.io/created-by: crh225