---
apiVersion: v1
kind: Namespace
metadata:
  name: portal-api
  labels:
    app.kubernetes.io/managed-by: crossplane
    app.kubernetes.io/name: portal-api
    armportal.chrishouse.io/component: api
---
apiVersion: platform.chrishouse.io/v1alpha1
kind: BackendClaim
metadata:
  name: portal-api
  namespace: portal-api
  labels:
    app.kubernetes.io/managed-by: crossplane
    app.kubernetes.io/name: portal-api
    armportal.chrishouse.io/component: api
spec:
  parameters:
    targetCluster: app-spoke
    image: armportalacre4k9.azurecr.io/armportal-api:latest
    replicas: 1
    port: 4000
    env: dev
    resources:
      cpuRequest: "100m"
      cpuLimit: "500m"
      memoryRequest: "256Mi"
      memoryLimit: "512Mi"
---
apiVersion: platform.chrishouse.io/v1alpha1
kind: IngressClaim
metadata:
  name: portal-api-ingress
  namespace: portal-api
  labels:
    app.kubernetes.io/managed-by: crossplane
    app.kubernetes.io/name: portal-api
    armportal.chrishouse.io/component: api
spec:
  parameters:
    targetCluster: app-spoke
    host: portal-api.chrishouse.io
    clusterIssuer: letsencrypt-prod
    paths:
      - path: /
        pathType: Prefix
        serviceName: portal-api
        servicePort: 80
