# Job to sync Cloudflare API token from Azure Key Vault to Kubernetes secret
# This job mounts the CSI volume and manually creates the Kubernetes secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-sync
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-sync
  namespace: cert-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-sync
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-sync
subjects:
  - kind: ServiceAccount
    name: secrets-sync
    namespace: cert-manager
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cert-manager-secrets-sync
  namespace: cert-manager
spec:
  template:
    spec:
      serviceAccountName: secrets-sync
      restartPolicy: OnFailure
      containers:
      - name: secrets-sync
        image: bitnami/kubectl:latest
        command:
          - /bin/bash
          - -c
          - |
            # Wait for CSI volume to be mounted
            while [ ! -f /mnt/secrets-store/CLOUDFLARE-API-TOKEN ]; do
              echo "Waiting for secrets to be mounted..."
              sleep 2
            done

            # Read the secret value from CSI mount
            TOKEN=$(cat /mnt/secrets-store/CLOUDFLARE-API-TOKEN)

            # Create or update the Kubernetes secret
            kubectl create secret generic cloudflare-api-token \
              --from-literal=api-token="$TOKEN" \
              --namespace=cert-manager \
              --dry-run=client -o yaml | kubectl apply -f -

            echo "Secret synced successfully from Azure Key Vault"
        volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "cert-manager-secrets"
