---
# Crossplane Kubernetes Provider
# Allows creating Kubernetes resources (Namespace, Deployment, Service, etc.) via Crossplane
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.14.1
  runtimeConfigRef:
    name: provider-kubernetes-config
---
# Runtime config for the Kubernetes provider
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-kubernetes-config
spec:
  serviceAccountTemplate:
    metadata:
      name: provider-kubernetes
---
# ProviderConfig for in-cluster access
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: InjectedIdentity
