# Namespace resource for ApplicationEnvironment
# Used by: application-environment-composition.yaml
resources:
  - name: namespace
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha2
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: ""
              labels:
                app.kubernetes.io/managed-by: crossplane
                platform.chrishouse.io/type: application-environment
                istio-injection: enabled
    patches:
      - type: PatchSet
        patchSetName: common-labels
      - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: spec.parameters.appName
            - fromFieldPath: spec.parameters.environment
          strategy: string
          string:
            fmt: "%s-%s"
        toFieldPath: spec.forProvider.manifest.metadata.name
      - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: spec.parameters.appName
            - fromFieldPath: spec.parameters.environment
          strategy: string
          string:
            fmt: "namespace-%s-%s"
        toFieldPath: metadata.name
