# PostgreSQL resources for ApplicationEnvironment
# Creates: PVC, Secret, Deployment, Service
resources:
  - name: postgres-pvc
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha2
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: ""
              labels:
                app.kubernetes.io/component: database
            spec:
              accessModes: [ReadWriteOnce]
              resources:
                requests:
                  storage: "10Gi"
              storageClassName: managed-csi
    patches:
      - type: PatchSet
        patchSetName: common-labels
      - type: PatchSet
        patchSetName: namespace-patch
      - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: spec.parameters.appName
            - fromFieldPath: spec.parameters.environment
          strategy: string
          string:
            fmt: "%s-%s-postgres-data"
        toFieldPath: spec.forProvider.manifest.metadata.name
      - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: spec.parameters.appName
            - fromFieldPath: spec.parameters.environment
          strategy: string
          string:
            fmt: "postgres-pvc-%s-%s"
        toFieldPath: metadata.name

  - name: postgres-secret
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha2
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: v1
            kind: Secret
            metadata:
              name: ""
              labels:
                app.kubernetes.io/component: database
            type: Opaque
            stringData:
              host: ""
              port: "5432"
              username: "postgres"
              password: "postgres123"
              database: "app"
    patches:
      - type: PatchSet
        patchSetName: common-labels
      - type: PatchSet
        patchSetName: namespace-patch
      - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: spec.parameters.appName
            - fromFieldPath: spec.parameters.environment
          strategy: string
          string:
            fmt: "%s-%s-db-credentials"
        toFieldPath: spec.forProvider.manifest.metadata.name
      - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: spec.parameters.appName
            - fromFieldPath: spec.parameters.environment
          strategy: string
          string:
            fmt: "postgres-secret-%s-%s"
        toFieldPath: metadata.name
      - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: spec.parameters.appName
            - fromFieldPath: spec.parameters.environment
          strategy: string
          string:
            fmt: "%s-%s-postgres"
        toFieldPath: spec.forProvider.manifest.stringData.host

  - name: postgres-deployment
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha2
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: ""
              labels:
                app.kubernetes.io/component: database
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app.kubernetes.io/component: database
              template:
                metadata:
                  labels:
                    app.kubernetes.io/component: database
                spec:
                  containers:
                    - name: postgres
                      image: postgres:16
                      ports:
                        - containerPort: 5432
                          name: postgres
                      env:
                        - { name: POSTGRES_USER, value: "postgres" }
                        - { name: POSTGRES_PASSWORD, value: "postgres123" }
                        - { name: POSTGRES_DB, value: "app" }
                        - { name: PGDATA, value: "/var/lib/postgresql/data/pgdata" }
                      volumeMounts:
                        - { name: postgres-data, mountPath: /var/lib/postgresql/data }
                      resources:
                        requests: { cpu: "200m", memory: "256Mi" }
                        limits: { cpu: "500m", memory: "512Mi" }
                  volumes:
                    - name: postgres-data
                      persistentVolumeClaim:
                        claimName: ""
    patches:
      - type: PatchSet
        patchSetName: common-labels
      - type: PatchSet
        patchSetName: namespace-patch
      - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: spec.parameters.appName
            - fromFieldPath: spec.parameters.environment
          strategy: string
          string:
            fmt: "%s-%s-postgres"
        toFieldPath: spec.forProvider.manifest.metadata.name
      - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: spec.parameters.appName
            - fromFieldPath: spec.parameters.environment
          strategy: string
          string:
            fmt: "postgres-deployment-%s-%s"
        toFieldPath: metadata.name
      - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: spec.parameters.appName
            - fromFieldPath: spec.parameters.environment
          strategy: string
          string:
            fmt: "%s-%s"
        toFieldPath: spec.forProvider.manifest.spec.selector.matchLabels["app.kubernetes.io/instance"]
      - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: spec.parameters.appName
            - fromFieldPath: spec.parameters.environment
          strategy: string
          string:
            fmt: "%s-%s"
        toFieldPath: spec.forProvider.manifest.spec.template.metadata.labels["app.kubernetes.io/instance"]
      - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: spec.parameters.appName
            - fromFieldPath: spec.parameters.environment
          strategy: string
          string:
            fmt: "%s-%s-postgres-data"
        toFieldPath: spec.forProvider.manifest.spec.template.spec.volumes[0].persistentVolumeClaim.claimName
      - type: FromCompositeFieldPath
        fromFieldPath: spec.parameters.database.version
        toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].image
        transforms:
          - type: string
            string:
              type: Format
              fmt: "postgres:%s"

  - name: postgres-service
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha2
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: v1
            kind: Service
            metadata:
              name: ""
              labels:
                app.kubernetes.io/component: database
            spec:
              type: ClusterIP
              ports:
                - { port: 5432, targetPort: 5432, protocol: TCP, name: postgres }
              selector:
                app.kubernetes.io/component: database
    patches:
      - type: PatchSet
        patchSetName: common-labels
      - type: PatchSet
        patchSetName: namespace-patch
      - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: spec.parameters.appName
            - fromFieldPath: spec.parameters.environment
          strategy: string
          string:
            fmt: "%s-%s-postgres"
        toFieldPath: spec.forProvider.manifest.metadata.name
      - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: spec.parameters.appName
            - fromFieldPath: spec.parameters.environment
          strategy: string
          string:
            fmt: "postgres-service-%s-%s"
        toFieldPath: metadata.name
      - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: spec.parameters.appName
            - fromFieldPath: spec.parameters.environment
          strategy: string
          string:
            fmt: "%s-%s"
        toFieldPath: spec.forProvider.manifest.spec.selector["app.kubernetes.io/instance"]
