# AnalysisTemplate for post-promotion monitoring
# Monitors production environment after promotion and triggers rollback if issues detected
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: production-health-monitor
  namespace: armportal-backend
spec:
  metrics:
  # Production health endpoint check
  - name: production-health
    interval: 30s
    count: 10
    successCondition: result == "200"
    failureLimit: 3
    provider:
      web:
        url: https://portal-api.chrishouse.io/api/health
        timeoutSeconds: 10
        jsonPath: "{$.status}"
        headers:
          - key: Content-Type
            value: application/json

  # Production HTTP status code check
  - name: production-http-status
    interval: 30s
    count: 10
    successCondition: result.startsWith("2")
    failureLimit: 3
    provider:
      web:
        url: https://portal-api.chrishouse.io/api/health
        timeoutSeconds: 10
        headers:
          - key: Content-Type
            value: application/json
        jsonPath: "{$.statusCode}"

  # Response time check - fail if response takes > 5 seconds
  - name: production-response-time
    interval: 30s
    count: 10
    successCondition: result < 5000
    failureLimit: 3
    provider:
      web:
        url: https://portal-api.chrishouse.io/api/health
        timeoutSeconds: 10
        headers:
          - key: Content-Type
            value: application/json
