# AnalysisTemplate for pre-promotion health checks
# Tests the preview environment before allowing promotion to production
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: preview-health-check
  namespace: armportal-backend
spec:
  metrics:
  # Health endpoint check - must return 200 OK
  - name: preview-health
    interval: 10s
    count: 6
    successCondition: result == "200"
    failureLimit: 2
    provider:
      web:
        url: https://portal-api-preview.chrishouse.io/api/health
        timeoutSeconds: 5
        jsonPath: "{$.status}"
        headers:
          - key: Content-Type
            value: application/json

  # HTTP status code check
  - name: preview-http-status
    interval: 10s
    count: 6
    successCondition: result.startsWith("2")
    failureLimit: 2
    provider:
      web:
        url: https://portal-api-preview.chrishouse.io/api/health
        timeoutSeconds: 5
        headers:
          - key: Content-Type
            value: application/json
        jsonPath: "{$.statusCode}"
