# ExternalSecret syncs secrets from Azure Key Vault to Kubernetes
# This replaces the manually created backend-secrets Secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets-sync
  namespace: armportal-backend
spec:
  # Refresh interval - check for updates every 5 minutes
  refreshInterval: 5m

  # Reference to the SecretStore
  secretStoreRef:
    name: azure-backend-secretstore
    kind: SecretStore

  # Target Kubernetes secret to create/update
  target:
    name: backend-secrets
    creationPolicy: Owner

  # Data to sync from Key Vault
  data:
    # Map Key Vault secret names to Kubernetes secret keys
    - secretKey: GH_APP_PRIVATE_KEY_BASE64
      remoteRef:
        key: GH-APP-PRIVATE-KEY-BASE64

    - secretKey: GH_OAUTH_CLIENT_SECRET
      remoteRef:
        key: GH-OAUTH-CLIENT-SECRET

    - secretKey: GITHUB_WEBHOOK_SECRET
      remoteRef:
        key: GITHUB-WEBHOOK-SECRET

    - secretKey: ELASTICSEARCH_API_KEY
      remoteRef:
        key: ELASTICSEARCH-API-KEY
