# SecretProviderClass for CSI Secret Store Driver
# Syncs secrets from Azure Key Vault to Kubernetes
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-backend-secrets
  namespace: armportal-backend
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "3e50729e-4a1f-42ab-aebb-9f80758b8c8d"
    keyvaultName: "akvnotintf1"
    tenantId: "354b7ce2-bca3-4af5-b19a-e05a09b68a7b"
    objects: |
      array:
        - |
          objectName: GH-APP-PRIVATE-KEY-BASE64
          objectType: secret
        - |
          objectName: GH-OAUTH-CLIENT-SECRET
          objectType: secret
        - |
          objectName: GITHUB-WEBHOOK-SECRET
          objectType: secret
        - |
          objectName: ELASTICSEARCH-API-KEY
          objectType: secret
        - |
          objectName: rabbitmq-url
          objectType: secret
        - |
          objectName: app-config-endpoint
          objectType: secret
  # Sync secrets to Kubernetes Secret
  secretObjects:
    - secretName: backend-secrets
      type: Opaque
      data:
        - objectName: GH-APP-PRIVATE-KEY-BASE64
          key: GH_APP_PRIVATE_KEY_BASE64
        - objectName: GH-OAUTH-CLIENT-SECRET
          key: GH_OAUTH_CLIENT_SECRET
        - objectName: GITHUB-WEBHOOK-SECRET
          key: GITHUB_WEBHOOK_SECRET
        - objectName: ELASTICSEARCH-API-KEY
          key: ELASTICSEARCH_API_KEY
        - objectName: rabbitmq-url
          key: RABBITMQ_URL
        - objectName: app-config-endpoint
          key: AZURE_APP_CONFIG_ENDPOINT
