# SecretStore configures External Secrets Operator to connect to Azure Key Vault
# This allows Kubernetes secrets to be synced from Azure Key Vault
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-backend-secretstore
  namespace: armportal-backend
spec:
  provider:
    azurekv:
      # Azure Key Vault URL
      vaultUrl: "https://akvnotintf1.vault.azure.net"

      # Azure Tenant ID
      tenantId: "354b7ce2-bca3-4af5-b19a-e05a09b68a7b"

      # Authentication via workload identity (AKS managed identity)
      authType: WorkloadIdentity

      # Service account that will be used for workload identity
      # This service account will be annotated with the Azure managed identity client ID
      serviceAccountRef:
        name: external-secrets-sa
