apiVersion: platform.chrishouse.io/v1alpha1
kind: NamespaceClaim
metadata:
  name: red-dev
  namespace: crossplane-system
  labels:
    team: red
    environment: dev
    created-by: backstage
    template: golden-path
  annotations:
    description: "Development namespace for red team"
    created-via: "backstage-golden-path-template"
    service: "shipping-api"
spec:
  parameters:
    targetCluster: shared-dev-cluster
    namespaceName: red-dev
    labels:
      team: red
      environment: dev
      managed-by: crossplane
      backstage.io/kubernetes-id: red

    # Enable all isolation features
    enableResourceQuota: true
    enableNetworkPolicy: true
    enableLimitRange: true

    # Default quotas for shared dev cluster (team-wide limits)
    resourceQuota:
      requestsCpu: "2"
      requestsMemory: "4Gi"
      limitsCpu: "4"
      limitsMemory: "8Gi"
      pods: 50

    # Default limits for individual containers
    limitRange:
      cpuRequest: "100m"
      cpuLimit: "500m"
      memoryRequest: "128Mi"
      memoryLimit: "512Mi"
