# Argo CD Application for Crossplane XRDs (Azure Resources)
# Defines the API schemas for Azure-based composite resources

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-xrds
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: crossplane
    app.kubernetes.io/component: xrds
spec:
  project: default

  source:
    repoURL: https://github.com/crh225/ARMServicePortal.git
    targetRevision: main
    path: infra/crossplane/xrds

  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system

  syncPolicy:
    automated:
      prune: true      # Delete resources removed from Git
      selfHeal: true   # Auto-sync when drift detected
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Required for XRDs/CRDs
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
