apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: "azure-storage-basic-e048de74"
  title: "Azure Storage Account (basic) - azure-storage-basic"
  description: "Creates a general-purpose v2 Storage Account with standard settings in an existing Resource Group. provisioned via ARM Portal"
  labels:
    armportal.chrishouse.io/blueprint: "azure-storage-basic"
    armportal.chrishouse.io/version: "1.0.0"
    armportal.chrishouse.io/environment: dev
    armportal.chrishouse.io/provider: terraform
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/crh225/ARMServicePortal/blob/main/infra/environments/dev/azure-storage-basic-e048de74.tf"
    backstage.io/managed-by-origin-location: "url:https://github.com/crh225/ARMServicePortal/blob/main/infra/environments/dev/azure-storage-basic-e048de74.tf"
    backstage.io/techdocs-ref: "url:https://github.com/crh225/ARMServicePortal/tree/main/docs"
    armportal.chrishouse.io/request-id: "256"
    armportal.chrishouse.io/created-by: crh225
    armportal.chrishouse.io/provisioned-at: "2025-12-09T23:02:24.056Z"
    armportal.chrishouse.io/terraform-module: "azure-storage-basic-e048de74"
    azure.com/resource-id: "/subscriptions/f989de0f-8697-4a05-8c34-b82c941767c0/resourceGroups/120420252-dev-rg/providers/Microsoft.Storage/storageAccounts/testsa12925"
    azure.com/resource-group-name: "120420252-dev-rg"
  tags:
    - azure
    - terraform
    - dev
    - storage
  links:
    - url: "https://github.com/crh225/ARMServicePortal/blob/main/infra/environments/dev/azure-storage-basic-e048de74.tf"
      title: Terraform Configuration
      icon: code
    - url: "https://github.com/crh225/ARMServicePortal/pull/256"
      title: Provisioning PR
      icon: github
    - url: "https://portal.azure.com/#@/resource/subscriptions/f989de0f-8697-4a05-8c34-b82c941767c0/resourceGroups/120420252-dev-rg/providers/Microsoft.Storage/storageAccounts/testsa12925"
      title: Azure Portal
      icon: cloud
spec:
  type: "azure-storage-account"
  lifecycle: development
  owner: "user:crh225"
  system: "testsa12925-dev"