apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: azure-rg-basic
  title: Azure Resource Group
  description: Creates a single Resource Group using a standardized naming convention.
  tags:
    - azure
    - infrastructure
    - resource-group
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: platform-team
  type: infrastructure

  parameters:
    - title: Resource Group Configuration
      required:
        - project_name
        - environment
        - location
      properties:
        project_name:
          title: Project Name
          type: string
          description: Name of your project
          ui:autofocus: true
        environment:
          title: Environment
          type: string
          description: Target environment
          default: dev
          enum:
            - dev
            - qa
            - staging
            - prod
          enumNames:
            - Development
            - QA
            - Staging
            - Production
        location:
          title: Azure Region
          type: string
          default: eastus2
          enum:
            - eastus
            - eastus2
            - westus
            - westus2
            - westus3
            - centralus
            - northcentralus
            - southcentralus
            - westcentralus
          enumNames:
            - East US
            - East US 2
            - West US
            - West US 2
            - West US 3
            - Central US
            - North Central US
            - South Central US
            - West Central US

  steps:
    - id: provision
      name: Provision Resource Group
      action: arm-portal:provision
      input:
        blueprintId: azure-rg-basic
        parameters:
          project_name: ${{ parameters.project_name }}
          environment: ${{ parameters.environment }}
          location: ${{ parameters.location }}

  output:
    links:
      - title: View Provisioning Job
        url: ${{ steps.provision.output.jobUrl }}
      - title: View Pull Request
        url: ${{ steps.provision.output.prUrl }}
