apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: promote-to-production
  title: Promote to Production
  description: Promote an existing service from development to the production cluster. Creates GitOps manifests for aks-app-spoke deployment.
  tags:
    - production
    - promotion
    - gitops
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Service to Promote
      required:
        - repo_url
        - service_name
        - team
      properties:
        repo_url:
          title: GitHub Repository URL
          type: string
          description: The GitHub repository containing your service (e.g., https://github.com/crh225/pricing-api)
          pattern: '^https://github\.com/[^/]+/[^/]+$'
          ui:autofocus: true
          ui:help: 'Must be a GitHub repository with a helm/ folder'

        service_name:
          title: Service Name
          type: string
          description: The name of your service (should match what's in catalog-info.yaml)
          pattern: '^[a-z][a-z0-9-]*$'

        team:
          title: Team
          type: string
          description: Which team owns this service?
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group

    - title: Production Configuration
      required:
        - replicas
        - initialVersion
      properties:
        initialVersion:
          title: Initial Version to Deploy
          type: string
          default: v1.0.0
          description: Semantic version tag for initial deployment (e.g., v1.0.0). Create this release in GitHub after PR is merged.
          pattern: '^v[0-9]+\.[0-9]+\.[0-9]+$'

        replicas:
          title: Number of Replicas
          type: integer
          description: For high availability, use at least 3 replicas
          default: 3
          minimum: 2
          maximum: 10

        enableHPA:
          title: Enable Horizontal Pod Autoscaling
          type: boolean
          default: true
          description: Automatically scale pods based on CPU usage

        maxReplicas:
          title: Maximum Replicas (for HPA)
          type: integer
          default: 10
          minimum: 3
          maximum: 50

        helmPath:
          title: Helm Chart Path
          type: string
          default: helm
          description: Path to Helm chart in your repository

    - title: Review & Confirm
      description: |
        **Production Deployment**

        Your service will be deployed to the production cluster (aks-app-spoke).
        This requires platform team approval before deployment.

        **Important:** After the PR is merged, you must create a GitHub Release
        with the version tag you specified (e.g., v1.0.0) to trigger the production build.
      required:
        - confirmReview
      properties:
        confirmReview:
          title: I confirm this service is ready for production
          type: boolean
          default: false
          ui:widget: checkbox

  steps:
    # Step 1: Create ArgoCD and Crossplane manifests
    - id: create-gitops
      name: Create GitOps Configuration
      action: fetch:template
      input:
        url: ./gitops-manifests
        targetPath: ./gitops/production-services/${{ parameters.service_name }}
        copyWithoutTemplating:
          - "virtualservice-hub.yaml"
          - "virtualservice-spoke.yaml"
        values:
          serviceName: ${{ parameters.service_name }}
          team: ${{ parameters.team | parseEntityRef | pick('name') }}
          repoUrl: ${{ parameters.repo_url }}
          namespace: ${{ parameters.team | parseEntityRef | pick('name') }}-prod
          targetCluster: aks-app-spoke
          replicas: ${{ parameters.replicas }}
          enableHPA: ${{ parameters.enableHPA }}
          maxReplicas: ${{ parameters.maxReplicas }}
          helmPath: ${{ parameters.helmPath }}
          initialVersion: ${{ parameters.initialVersion }}

    # Step 2: Create Hub VirtualService (routes external traffic to spoke)
    - id: create-hub-vs
      name: Create Hub Ingress Route
      action: fetch:template
      input:
        url: ./hub-virtualservice
        targetPath: ./gitops/kubernetes/istio-hub
        values:
          serviceName: ${{ parameters.service_name }}
          team: ${{ parameters.team | parseEntityRef | pick('name') }}

    # Step 3: Create Spoke VirtualService (routes to actual service)
    - id: create-spoke-vs
      name: Create Spoke Ingress Route
      action: fetch:template
      input:
        url: ./spoke-virtualservice
        targetPath: ./gitops/kubernetes/istio-spoke
        values:
          serviceName: ${{ parameters.service_name }}
          team: ${{ parameters.team | parseEntityRef | pick('name') }}
          namespace: ${{ parameters.team | parseEntityRef | pick('name') }}-prod

    # Step 4: Fetch existing kustomization files to append new VirtualService entries
    - id: fetch-existing-kustomize
      name: Fetch Existing Kustomization Files
      action: fetch:plain
      input:
        url: https://github.com/crh225/ARMServicePortal/tree/main/infra/kubernetes
        targetPath: ./gitops/kubernetes

    # Step 5: Append VirtualService to hub kustomization.yaml
    - id: append-hub-kustomize
      name: Add VirtualService to Hub Kustomization
      action: roadiehq:utils:fs:append
      input:
        path: ./gitops/kubernetes/istio-hub/kustomization.yaml
        content: |
            - virtualservice-${{ parameters.service_name }}-prod.yaml

    # Step 6: Append VirtualService to spoke kustomization.yaml
    - id: append-spoke-kustomize
      name: Add VirtualService to Spoke Kustomization
      action: roadiehq:utils:fs:append
      input:
        path: ./gitops/kubernetes/istio-spoke/kustomization.yaml
        content: |
            - virtualservice-${{ parameters.service_name }}-prod.yaml

    # Step 7: Create pull request in ARMServicePortal repo
    - id: publish-gitops
      name: Submit GitOps PR (Requires Approval)
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=crh225&repo=ARMServicePortal
        branchName: production/${{ parameters.service_name }}
        title: 'PRODUCTION: Promote ${{ parameters.service_name }} to production cluster'
        description: |
          ## Production Promotion Request: ${{ parameters.service_name }}

          **REQUIRES PLATFORM TEAM APPROVAL**

          This promotes an existing service to the production cluster using trunk-based release flow.

          ---

          ### Service Information

          | Field | Value |
          |-------|-------|
          | **Service Name** | ${{ parameters.service_name }} |
          | **Team** | ${{ parameters.team }} |
          | **Source Repository** | ${{ parameters.repo_url }} |
          | **Initial Version** | ${{ parameters.initialVersion }} |

          ---

          ### Production Configuration

          | Field | Value |
          |-------|-------|
          | **Target Cluster** | aks-app-spoke |
          | **Namespace** | ${{ parameters.team }}-prod |
          | **Replicas** | ${{ parameters.replicas }} |
          | **HPA Enabled** | ${{ parameters.enableHPA }} |
          | **Max Replicas** | ${{ parameters.maxReplicas }} |
          | **Production URL** | https://${{ parameters.service_name }}-prod.chrishouse.io |

          ---

          ### Release Flow (Trunk-Based)

          Once merged, production releases work as follows:

          1. **Create a GitHub Release** in your service repo with tag `${{ parameters.initialVersion }}`
          2. CI builds and pushes image tagged `${{ parameters.initialVersion }}`
          3. ArgoCD detects the new image and deploys to production

          **For future releases:**
          - Create new GitHub Release (e.g., `v1.1.0`, `v1.2.0`)
          - CI automatically builds and pushes the new version
          - Update the ArgoCD manifest to use the new version tag

          ---

          ### Approval Checklist

          - [ ] Service has been tested in development
          - [ ] Resource limits are appropriate for production
          - [ ] Team has budget approval
          - [ ] Ready to create GitHub Release `${{ parameters.initialVersion }}` after merge

          ---
          Created via Backstage Promote to Production Template
        sourcePath: ./gitops
        targetPath: infra

  output:
    links:
      - title: GitOps PR (Requires Approval)
        url: ${{ steps['publish-gitops'].output.remoteUrl }}
      - title: Source Repository
        url: ${{ parameters.repo_url }}
      - title: Production URL (after merge)
        url: https://${{ parameters.service_name }}-prod.chrishouse.io
    text:
      - title: Next Steps
        content: |
          ## Production Promotion: ${{ parameters.service_name }}

          **GitOps PR created:** ${{ steps['publish-gitops'].output.remoteUrl }}

          ### What happens next:

          1. **Platform team reviews** the GitOps PR
          2. **PR is merged** after approval
          3. **You create a GitHub Release** with tag `${{ parameters.initialVersion }}` in your service repo
          4. **CI builds** the production image with that version tag
          5. **ArgoCD deploys** to aks-app-spoke cluster
          6. **Service available at:** https://${{ parameters.service_name }}-prod.chrishouse.io

          ### Future Releases

          To deploy new versions to production:
          1. Create a new GitHub Release (e.g., v1.1.0)
          2. Update the image tag in the ArgoCD manifest (or use ArgoCD Image Updater)
