---
apiVersion: v1
kind: Namespace
metadata:
  name: "aredis-staging"
  labels:
    app.kubernetes.io/managed-by: crossplane
    app.kubernetes.io/name: aredis
    app.kubernetes.io/instance: "aredis-staging"
    armportal.chrishouse.io/blueprint: "xp-building-blocks"
    armportal.chrishouse.io/version: "2.0.0"
    armportal.chrishouse.io/request-id: 236cabce
    armportal.chrishouse.io/created-by: crh225
    istio-injection: enabled
---
apiVersion: platform.chrishouse.io/v1alpha1
kind: RedisClaim
metadata:
  name: "aredis-cache"
  namespace: "aredis-staging"
  labels:
    app.kubernetes.io/managed-by: armportal
    app.kubernetes.io/name: aredis
    app.kubernetes.io/instance: "aredis-staging"
    armportal.chrishouse.io/blueprint: "xp-building-blocks"
    armportal.chrishouse.io/version: "2.0.0"
    armportal.chrishouse.io/request-id: 236cabce
    armportal.chrishouse.io/created-by: crh225
    armportal.chrishouse.io/component: redis
spec:
  parameters:
    version: "7.2"
    memoryLimitMB: 256