apiVersion: armportal.io/v1alpha1
kind: ContainerApp
metadata:
  name: armportal-backend
  namespace: default
spec:
  parameters:
    appName: armportal-api-crossplane
    resourceGroupName: rg-armportal-crossplane-demo
    location: "East US"
    # Get this after creating the environment with containerapp-environment.yaml
    # kubectl get containerenvironment demo-environment -o jsonpath='{.status.environmentId}'
    environmentId: "/subscriptions/YOUR_SUBSCRIPTION_ID/resourceGroups/rg-armportal-crossplane-demo/providers/Microsoft.App/managedEnvironments/armportal-demo-env"

    # Update with your ACR image - matches your Terraform setup
    # Currently your Terraform uses: mcr.microsoft.com/azuredocs/containerapps-helloworld:latest
    # Change to: armportalacr<suffix>.azurecr.io/armportal-api:latest
    containerImage: "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"

    # Port configuration - matches your Dockerfile and Terraform (port 4000)
    containerPort: 4000

    # Resource sizing - matches your Terraform
    cpu: 0.5
    memory: "1Gi"

    # Scaling - matches your Terraform (1-2 replicas)
    minReplicas: 1
    maxReplicas: 2

    # Ingress - external access enabled
    ingressEnabled: true
    externalIngress: true

    # Environment variables - these match your backend-containerapps.tf
    # NOTE: Secrets (GH_APP_PRIVATE_KEY_BASE64, GITHUB_WEBHOOK_SECRET, ELASTICSEARCH_API_KEY)
    # would need to be configured separately via Kubernetes secrets in Crossplane
    # environmentVariables:
    #   NODE_ENV: "production"
    #   GH_INFRA_OWNER: "crh225"
    #   GH_INFRA_REPO: "ARMServicePortal"
    #   GH_APP_ID: "your-app-id"
    #   GH_INSTALLATION_ID: "your-installation-id"
    #   FRONTEND_URL: "https://portal.chrishouse.io"
    #   ELASTICSEARCH_URL: "your-elasticsearch-endpoint"
    #   APP_NAME: "arm-service-portal"
