apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.storageAccountName }}
  description: Azure Storage Account provisioned via Crossplane
  annotations:
    backstage.io/managed-by-location: url:https://github.com/crh225/ARMServicePortal/blob/main/infra/crossplane/claims/${{ values.storageAccountName }}/claim.yaml
  labels:
    crossplane.io/claim-name: ${{ values.storageAccountName }}
  tags:
    - crossplane
    - azure
    - storage
spec:
  type: storage
  lifecycle: production
  owner: ${{ values.owner | default('platform-team', true) }}
  system: azure-infrastructure
