---
apiVersion: armportal.io/v1alpha1
kind: StorageAccount
metadata:
  name: ${{ values.storageAccountName }}
  namespace: crossplane-system
  labels:
    app.kubernetes.io/managed-by: crossplane
    app.kubernetes.io/name: ${{ values.storageAccountName }}
    armportal.chrishouse.io/environment: ${{ values.environment }}
    armportal.chrishouse.io/created-by: backstage
spec:
  parameters:
    storageAccountName: ${{ values.storageAccountName }}
    resourceGroupName: ${{ values.resourceGroupName }}
    tier: ${{ values.tier }}
    replicationType: ${{ values.replicationType }}
    location: ${{ values.location }}
  writeConnectionSecretToRef:
    name: ${{ values.storageAccountName }}-conn
