# ArgoCD Project for Team: pep
# Provides namespace isolation and access control
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-pep
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: team-pep
    armportal.chrishouse.io/team: pep
    armportal.chrishouse.io/managed-by: backstage
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for team pep - This is the first attempt at generating a golden path repo/pipeline and service

  # Allowed source repositories
  sourceRepos:
    - https://github.com/crh225/ARMServicePortal.git
    - 'https://github.com/crh225/team-pep-*'

  # Allowed deployment destinations
  destinations:
    # Team namespace for workloads
    - namespace: team-pep
      server: https://kubernetes.default.svc
    # ArgoCD namespace for child Applications
    - namespace: argocd
      server: https://kubernetes.default.svc

  # Cluster-scoped resources the team can create
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    # Crossplane resources (cluster-scoped)
    - group: azure.upbound.io
      kind: ResourceGroup
    - group: storage.azure.upbound.io
      kind: Account
    - group: keyvault.azure.upbound.io
      kind: Vault
    - group: appconfiguration.azure.upbound.io
      kind: Configuration

  # Namespace-scoped resources (allow all within their namespace)
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  # Deny dangerous cluster resources
  clusterResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding

  # Orphaned resource monitoring
  orphanedResources:
    warn: true
