# Argo CD Application for Istio Spoke Gateway Configuration
# Deploys internal Gateway and VirtualServices to spoke cluster

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-spoke
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/crh225/ARMServicePortal.git
    targetRevision: main
    path: infra/kubernetes/istio-spoke

  destination:
    name: aks-app-spoke
    namespace: istio-ingress

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
