# Argo CD Application for Istio Hub Gateway Configuration
# Deploys Gateway, VirtualServices, and ServiceEntry to hub cluster for external ingress

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-hub
  namespace: argocd
spec:
  project: platform-infrastructure

  source:
    repoURL: https://github.com/crh225/ARMServicePortal.git
    targetRevision: main
    path: infra/kubernetes/istio-hub

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
