# Composite Resource Definition for Azure Container App
# Allows deploying containerized applications to Azure Container Apps
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcontainerapps.armportal.io
spec:
  group: armportal.io
  names:
    kind: XContainerApp
    plural: xcontainerapps
  claimNames:
    kind: ContainerApp
    plural: containerapps
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    appName:
                      type: string
                      description: Name of the container app
                      pattern: '^[a-z0-9]([a-z0-9-]{0,30}[a-z0-9])?$'
                    location:
                      type: string
                      description: Azure region
                      default: "East US"
                    resourceGroupName:
                      type: string
                      description: Resource group name
                    environmentId:
                      type: string
                      description: Container Apps Environment ID
                    containerImage:
                      type: string
                      description: Container image (e.g., nginx:latest, mcr.microsoft.com/azuredocs/containerapps-helloworld:latest)
                    containerPort:
                      type: integer
                      description: Port the container listens on
                      default: 80
                      minimum: 1
                      maximum: 65535
                    cpu:
                      type: number
                      description: CPU cores (0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0)
                      default: 0.5
                      enum: [0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0]
                    memory:
                      type: string
                      description: Memory allocation (e.g., 0.5Gi, 1Gi, 1.5Gi, 2Gi, 3Gi, 4Gi)
                      default: "1Gi"
                      pattern: '^[0-9]+(\.[0-9]+)?Gi$'
                    minReplicas:
                      type: integer
                      description: Minimum number of replicas
                      default: 1
                      minimum: 0
                      maximum: 30
                    maxReplicas:
                      type: integer
                      description: Maximum number of replicas
                      default: 10
                      minimum: 1
                      maximum: 30
                    ingressEnabled:
                      type: boolean
                      description: Enable ingress (HTTP/HTTPS traffic)
                      default: true
                    externalIngress:
                      type: boolean
                      description: Enable external ingress (public internet)
                      default: true
                    environmentVariables:
                      type: object
                      description: Environment variables for the container
                      additionalProperties:
                        type: string
                  required:
                    - appName
                    - resourceGroupName
                    - environmentId
                    - containerImage
              required:
                - parameters
