apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rg-crossplane-dev
  description: Azure Resource Group provisioned via Crossplane
  annotations:
    backstage.io/managed-by-location: url:https://github.com/crh225/ARMServicePortal/blob/main/infra/crossplane/claims/rg-crossplane-dev/claims.yaml
  labels:
    crossplane.io/claim-name: rg-crossplane-dev
  tags:
    - crossplane
    - azure
    - resource-group
spec:
  type: resource-group
  lifecycle: production
  owner: group:default/crh225
  system: azure-infrastructure
