apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: "xztest-dev"
  title: xztest (dev)
  description: "Full-stack application deployed via ARM Portal Building Blocks"
  labels:
    armportal.chrishouse.io/blueprint: "xp-building-blocks"
    armportal.chrishouse.io/environment: dev
    armportal.chrishouse.io/provider: crossplane
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/crh225/ARMServicePortal/blob/main/infra/crossplane/claims/xztest-dev/claims.yaml"
    backstage.io/managed-by-origin-location: "url:https://github.com/crh225/ARMServicePortal/blob/main/infra/crossplane/claims/xztest-dev/claims.yaml"
    armportal.chrishouse.io/request-id: "244"
    armportal.chrishouse.io/created-by: backstage
    armportal.chrishouse.io/provisioned-at: "2025-12-05T02:35:03.161Z"
  tags:
    - kubernetes
    - crossplane
    - dev
    - "building-blocks"
  links:
    - url: "https://github.com/crh225/ARMServicePortal/blob/main/infra/crossplane/claims/xztest-dev/claims.yaml"
      title: Crossplane Claims
      icon: code
    - url: "https://github.com/crh225/ARMServicePortal/pull/244"
      title: Provisioning PR
      icon: github
spec:
  owner: "user:backstage"
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: "xztest-cache-dev"
  title: xztest Redis (dev)
  description: Redis component for xztest
  labels:
    armportal.chrishouse.io/blueprint: "xp-building-blocks"
    armportal.chrishouse.io/component: redis
    armportal.chrishouse.io/environment: dev
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/crh225/ARMServicePortal/blob/main/infra/crossplane/claims/xztest-dev/claims.yaml"
    backstage.io/managed-by-origin-location: "url:https://github.com/crh225/ARMServicePortal/blob/main/infra/crossplane/claims/xztest-dev/claims.yaml"
    backstage.io/kubernetes-id: "xztest-cache"
    backstage.io/kubernetes-namespace: "xztest-dev"
  tags:
    - kubernetes
    - crossplane
    - dev
    - redis
spec:
  type: cache
  lifecycle: development
  owner: "user:backstage"
  system: "xztest-dev"