apiVersion: platform.chrishouse.io/v1alpha1
kind: RabbitMQClaim
metadata:
  name: "xp-rabbitmq_e5c25a90"
  namespace: "platform-claims"
  labels:
    app.kubernetes.io/managed-by: armportal
    armportal.chrishouse.io/blueprint: "xp-rabbitmq"
    armportal.chrishouse.io/version: "0.0.1"
    armportal.chrishouse.io/request-id: "176"
    armportal.chrishouse.io/created-by: crh225
  annotations:
    armportal.chrishouse.io/provisioned-at: "2025-11-28T02:01:22.386Z"
spec:
  parameters:
    name: "test-rabbit-xp"
    environment: dev
    storageGB: 5
    rabbitmqVersion: "3.13"
    memoryLimitMB: "512"
    adminUsername: chance
  writeConnectionSecretToRef:
    name: "xp-rabbitmq_e5c25a90-connection"
  compositionRef:
    name: rabbitmq