---
apiVersion: v1
kind: Namespace
metadata:
  name: "xtest-dev"
  labels:
    app.kubernetes.io/managed-by: crossplane
    app.kubernetes.io/name: xtest
    app.kubernetes.io/instance: "xtest-dev"
    armportal.chrishouse.io/blueprint: "xp-building-blocks"
    armportal.chrishouse.io/version: "2.0.0"
    armportal.chrishouse.io/request-id: "205"
    armportal.chrishouse.io/created-by: crh225
    istio-injection: enabled
---
apiVersion: platform.chrishouse.io/v1alpha1
kind: RedisClaim
metadata:
  name: "xtest-cache"
  namespace: "xtest-dev"
  labels:
    app.kubernetes.io/managed-by: armportal
    app.kubernetes.io/name: xtest
    app.kubernetes.io/instance: "xtest-dev"
    armportal.chrishouse.io/blueprint: "xp-building-blocks"
    armportal.chrishouse.io/version: "2.0.0"
    armportal.chrishouse.io/request-id: "205"
    armportal.chrishouse.io/created-by: crh225
    armportal.chrishouse.io/component: redis
spec:
  parameters:
    version: "7.2"
    memoryLimitMB: 256
---
apiVersion: platform.chrishouse.io/v1alpha1
kind: RabbitMQClaim
metadata:
  name: "xtest-mq"
  namespace: "xtest-dev"
  labels:
    app.kubernetes.io/managed-by: armportal
    app.kubernetes.io/name: xtest
    app.kubernetes.io/instance: "xtest-dev"
    armportal.chrishouse.io/blueprint: "xp-building-blocks"
    armportal.chrishouse.io/version: "2.0.0"
    armportal.chrishouse.io/request-id: "205"
    armportal.chrishouse.io/created-by: crh225
    armportal.chrishouse.io/component: rabbitmq
spec:
  parameters:
    version: "3.13"
    memoryLimitMB: 512
    exposeManagement: true
---
apiVersion: platform.chrishouse.io/v1alpha1
kind: BackendClaim
metadata:
  name: "xtest-backend"
  namespace: "xtest-dev"
  labels:
    app.kubernetes.io/managed-by: armportal
    app.kubernetes.io/name: xtest
    app.kubernetes.io/instance: "xtest-dev"
    armportal.chrishouse.io/blueprint: "xp-building-blocks"
    armportal.chrishouse.io/version: "2.0.0"
    armportal.chrishouse.io/request-id: "205"
    armportal.chrishouse.io/created-by: crh225
    armportal.chrishouse.io/component: backend
spec:
  parameters:
    image: "armportalacre4k9.azurecr.io/armportal-api-backend:latest"
    replicas: 2
    port: 4000
    env: dev
---
apiVersion: platform.chrishouse.io/v1alpha1
kind: FrontendClaim
metadata:
  name: "xtest-frontend"
  namespace: "xtest-dev"
  labels:
    app.kubernetes.io/managed-by: armportal
    app.kubernetes.io/name: xtest
    app.kubernetes.io/instance: "xtest-dev"
    armportal.chrishouse.io/blueprint: "xp-building-blocks"
    armportal.chrishouse.io/version: "2.0.0"
    armportal.chrishouse.io/request-id: "205"
    armportal.chrishouse.io/created-by: crh225
    armportal.chrishouse.io/component: frontend
spec:
  parameters:
    image: "armportalacre4k9.azurecr.io/armportal-backend:latest"
    replicas: 2
    backendUrl: "http://xtest-backend"