apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: team-${{ values.teamName }}-${{ values.appName }}
  title: ${{ values.teamName }} - ${{ values.appName }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: crh225/team-${{ values.teamName }}-${{ values.appName }}
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: team-${{ values.teamName }}-${{ values.appName }}
  tags:
    - team-${{ values.teamName }}
    - node
{%- if values.app_type == 'static' %}
    - static-site
{%- else %}
    - server
{%- endif %}
  links:
    - url: https://${{ values.domain }}
      title: Live Site
      icon: dashboard
    - url: https://argocd.chrishouse.io/applications/team-${{ values.teamName }}
      title: Team ArgoCD Apps
      icon: cloud
    - url: https://portal.azure.com/#@/resource/subscriptions/f989de0f-8697-4a05-8c34-b82c941767c0/resourceGroups/${{ values.resourceGroupName }}
      title: Azure Resource Group
      icon: cloud
spec:
  type: website
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: team-${{ values.teamName }}
