apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xaksclusters.platform.chrishouse.io
spec:
  group: platform.chrishouse.io
  names:
    kind: XAKSCluster
    plural: xaksclusters
  claimNames:
    kind: AKSCluster
    plural: aksclusters
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                location:
                  type: string
                  default: eastus
                resourceGroupName:
                  type: string
                nodeCount:
                  type: integer
                  default: 1
                vmSize:
                  type: string
                  default: Standard_B2s
                kubernetesVersion:
                  type: string
                  default: "1.32"
                subnetId:
                  type: string
                serviceCidr:
                  type: string
                  default: "10.101.0.0/16"
                dnsServiceIp:
                  type: string
                  default: "10.101.0.10"
              required:
                - resourceGroupName
                - subnetId
            status:
              type: object
              properties:
                clusterFqdn:
                  type: string
                kubeConfigSecretRef:
                  type: string
