---
# Backend Composition - Building Block
# Creates: Deployment, Service
# Namespace comes from the claim's namespace
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbackend
  labels:
    crossplane.io/xrd: xbackends.platform.chrishouse.io
spec:
  compositeTypeRef:
    apiVersion: platform.chrishouse.io/v1alpha1
    kind: XBackend
  mode: Pipeline
  pipeline:
    - step: backend-resources
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          # Deployment
          - name: deployment
            base:
              apiVersion: kubernetes.crossplane.io/v1alpha2
              kind: Object
              spec:
                forProvider:
                  manifest:
                    apiVersion: apps/v1
                    kind: Deployment
                    metadata:
                      labels:
                        app.kubernetes.io/component: backend
                        app.kubernetes.io/managed-by: crossplane
                    spec:
                      replicas: 2
                      selector:
                        matchLabels:
                          app.kubernetes.io/component: backend
                      template:
                        metadata:
                          labels:
                            app.kubernetes.io/component: backend
                        spec:
                          containers:
                            - name: backend
                              ports: [{ containerPort: 4000 }]
                              env:
                                - name: NODE_ENV
                                  value: development
                              resources:
                                requests: { cpu: "200m", memory: "256Mi" }
                                limits: { cpu: "500m", memory: "512Mi" }
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-namespace"]
                toFieldPath: spec.forProvider.manifest.metadata.namespace
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-name"]
                toFieldPath: spec.forProvider.manifest.metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string: { type: Format, fmt: "%s-deploy" }
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.image
                toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].image
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.replicas
                toFieldPath: spec.forProvider.manifest.spec.replicas
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.port
                toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].ports[0].containerPort
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.env
                toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].env[0].value
                transforms:
                  - type: map
                    map:
                      dev: development
                      staging: staging
                      prod: production
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-name"]
                toFieldPath: spec.forProvider.manifest.spec.selector.matchLabels["app.kubernetes.io/instance"]
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-name"]
                toFieldPath: spec.forProvider.manifest.spec.template.metadata.labels["app.kubernetes.io/instance"]

          # Service
          - name: service
            base:
              apiVersion: kubernetes.crossplane.io/v1alpha2
              kind: Object
              spec:
                forProvider:
                  manifest:
                    apiVersion: v1
                    kind: Service
                    metadata:
                      labels:
                        app.kubernetes.io/component: backend
                        app.kubernetes.io/managed-by: crossplane
                    spec:
                      type: ClusterIP
                      ports: [{ port: 80, targetPort: 4000 }]
                      selector:
                        app.kubernetes.io/component: backend
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-namespace"]
                toFieldPath: spec.forProvider.manifest.metadata.namespace
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-name"]
                toFieldPath: spec.forProvider.manifest.metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string: { type: Format, fmt: "%s-svc" }
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.port
                toFieldPath: spec.forProvider.manifest.spec.ports[0].targetPort
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-name"]
                toFieldPath: spec.forProvider.manifest.spec.selector["app.kubernetes.io/instance"]

    # Optional: Add DB env vars if dbSecretName is provided
    - step: db-env-vars
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- $xr := .observed.composite.resource }}
            {{- $dbSecret := $xr.spec.parameters.dbSecretName }}
            {{- if $dbSecret }}
            {{- $ns := index $xr.metadata.labels "crossplane.io/claim-namespace" }}
            {{- $name := index $xr.metadata.labels "crossplane.io/claim-name" }}
            {{- /* Patch the deployment to add DB env vars */ -}}
            {{- range $key, $val := .observed.resources }}
            {{- if eq $key "deployment" }}
            ---
            apiVersion: kubernetes.crossplane.io/v1alpha2
            kind: Object
            metadata:
              name: {{ $xr.metadata.name }}-deploy
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: deployment
            spec:
              forProvider:
                manifest:
                  apiVersion: apps/v1
                  kind: Deployment
                  metadata:
                    name: {{ $name }}
                    namespace: {{ $ns }}
                    labels:
                      app.kubernetes.io/component: backend
                      app.kubernetes.io/managed-by: crossplane
                  spec:
                    replicas: {{ default 2 $xr.spec.parameters.replicas }}
                    selector:
                      matchLabels:
                        app.kubernetes.io/component: backend
                        app.kubernetes.io/instance: {{ $name }}
                    template:
                      metadata:
                        labels:
                          app.kubernetes.io/component: backend
                          app.kubernetes.io/instance: {{ $name }}
                      spec:
                        containers:
                          - name: backend
                            image: {{ $xr.spec.parameters.image }}
                            ports: [{ containerPort: {{ default 4000 $xr.spec.parameters.port }} }]
                            env:
                              - name: NODE_ENV
                                value: {{ default "development" (index (dict "dev" "development" "staging" "staging" "prod" "production") (default "dev" $xr.spec.parameters.env)) }}
                              - name: DATABASE_HOST
                                valueFrom: { secretKeyRef: { name: {{ $dbSecret }}, key: host } }
                              - name: DATABASE_PORT
                                valueFrom: { secretKeyRef: { name: {{ $dbSecret }}, key: port } }
                              - name: DATABASE_USER
                                valueFrom: { secretKeyRef: { name: {{ $dbSecret }}, key: username } }
                              - name: DATABASE_PASSWORD
                                valueFrom: { secretKeyRef: { name: {{ $dbSecret }}, key: password } }
                              - name: DATABASE_NAME
                                valueFrom: { secretKeyRef: { name: {{ $dbSecret }}, key: database } }
                            resources:
                              requests: { cpu: "200m", memory: "256Mi" }
                              limits: { cpu: "500m", memory: "512Mi" }
            {{- end }}
            {{- end }}
            {{- end }}
