---
# Frontend Composition - Building Block
# Creates: Deployment, Service
# Namespace comes from the claim's namespace
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xfrontend
  labels:
    crossplane.io/xrd: xfrontends.platform.chrishouse.io
spec:
  compositeTypeRef:
    apiVersion: platform.chrishouse.io/v1alpha1
    kind: XFrontend
  mode: Pipeline
  pipeline:
    - step: frontend-resources
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          # Deployment
          - name: deployment
            base:
              apiVersion: kubernetes.crossplane.io/v1alpha2
              kind: Object
              spec:
                providerConfigRef:
                  name: default
                forProvider:
                  manifest:
                    apiVersion: apps/v1
                    kind: Deployment
                    metadata:
                      labels:
                        app.kubernetes.io/component: frontend
                        app.kubernetes.io/managed-by: crossplane
                    spec:
                      replicas: 2
                      selector:
                        matchLabels:
                          app.kubernetes.io/component: frontend
                      template:
                        metadata:
                          labels:
                            app.kubernetes.io/component: frontend
                        spec:
                          containers:
                            - name: frontend
                              ports: [{ containerPort: 80 }]
                              env:
                                - name: BACKEND_URL
                                  value: ""
                              resources:
                                requests: { cpu: "100m", memory: "128Mi" }
                                limits: { cpu: "200m", memory: "256Mi" }
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.targetCluster
                toFieldPath: spec.providerConfigRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-namespace"]
                toFieldPath: spec.forProvider.manifest.metadata.namespace
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-name"]
                toFieldPath: spec.forProvider.manifest.metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string: { type: Format, fmt: "%s-deploy" }
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.image
                toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].image
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.replicas
                toFieldPath: spec.forProvider.manifest.spec.replicas
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.port
                toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].ports[0].containerPort
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.backendUrl
                toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].env[0].value
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-name"]
                toFieldPath: spec.forProvider.manifest.spec.selector.matchLabels["app.kubernetes.io/instance"]
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-name"]
                toFieldPath: spec.forProvider.manifest.spec.template.metadata.labels["app.kubernetes.io/instance"]

          # Service
          - name: service
            base:
              apiVersion: kubernetes.crossplane.io/v1alpha2
              kind: Object
              spec:
                providerConfigRef:
                  name: default
                forProvider:
                  manifest:
                    apiVersion: v1
                    kind: Service
                    metadata:
                      labels:
                        app.kubernetes.io/component: frontend
                        app.kubernetes.io/managed-by: crossplane
                    spec:
                      type: ClusterIP
                      ports: [{ port: 80, targetPort: 80 }]
                      selector:
                        app.kubernetes.io/component: frontend
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.targetCluster
                toFieldPath: spec.providerConfigRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-namespace"]
                toFieldPath: spec.forProvider.manifest.metadata.namespace
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-name"]
                toFieldPath: spec.forProvider.manifest.metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string: { type: Format, fmt: "%s-svc" }
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.port
                toFieldPath: spec.forProvider.manifest.spec.ports[0].targetPort
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-name"]
                toFieldPath: spec.forProvider.manifest.spec.selector["app.kubernetes.io/instance"]
