---
# Postgres Composition - Building Block
# Creates: PVC, Secret, Deployment, Service
# Namespace comes from the claim's namespace
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xpostgres
  labels:
    crossplane.io/xrd: xpostgres.platform.chrishouse.io
spec:
  compositeTypeRef:
    apiVersion: platform.chrishouse.io/v1alpha1
    kind: XPostgres
  writeConnectionSecretsToNamespace: crossplane-system
  mode: Pipeline
  pipeline:
    - step: postgres-resources
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          # PVC
          - name: pvc
            base:
              apiVersion: kubernetes.crossplane.io/v1alpha2
              kind: Object
              spec:
                forProvider:
                  manifest:
                    apiVersion: v1
                    kind: PersistentVolumeClaim
                    metadata:
                      labels:
                        app.kubernetes.io/component: database
                        app.kubernetes.io/managed-by: crossplane
                    spec:
                      accessModes: [ReadWriteOnce]
                      storageClassName: managed-csi
                      resources:
                        requests:
                          storage: "10Gi"
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-namespace"]
                toFieldPath: spec.forProvider.manifest.metadata.namespace
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-name"]
                toFieldPath: spec.forProvider.manifest.metadata.name
                transforms:
                  - type: string
                    string: { type: Format, fmt: "%s-data" }
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string: { type: Format, fmt: "%s-pvc" }
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.storageGB
                toFieldPath: spec.forProvider.manifest.spec.resources.requests.storage
                transforms:
                  - type: string
                    string: { type: Format, fmt: "%dGi" }

          # Secret
          - name: secret
            base:
              apiVersion: kubernetes.crossplane.io/v1alpha2
              kind: Object
              spec:
                forProvider:
                  manifest:
                    apiVersion: v1
                    kind: Secret
                    metadata:
                      labels:
                        app.kubernetes.io/component: database
                        app.kubernetes.io/managed-by: crossplane
                    type: Opaque
                    stringData:
                      host: ""
                      port: "5432"
                      username: postgres
                      password: postgres123
                      database: app
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-namespace"]
                toFieldPath: spec.forProvider.manifest.metadata.namespace
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-name"]
                toFieldPath: spec.forProvider.manifest.metadata.name
                transforms:
                  - type: string
                    string: { type: Format, fmt: "%s-credentials" }
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string: { type: Format, fmt: "%s-secret" }
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-name"]
                toFieldPath: spec.forProvider.manifest.stringData.host

          # Deployment
          - name: deployment
            base:
              apiVersion: kubernetes.crossplane.io/v1alpha2
              kind: Object
              spec:
                forProvider:
                  manifest:
                    apiVersion: apps/v1
                    kind: Deployment
                    metadata:
                      labels:
                        app.kubernetes.io/component: database
                        app.kubernetes.io/managed-by: crossplane
                    spec:
                      replicas: 1
                      selector:
                        matchLabels:
                          app.kubernetes.io/component: database
                      template:
                        metadata:
                          labels:
                            app.kubernetes.io/component: database
                        spec:
                          containers:
                            - name: postgres
                              image: postgres:16
                              ports: [{ containerPort: 5432 }]
                              env:
                                - { name: POSTGRES_USER, value: postgres }
                                - { name: POSTGRES_PASSWORD, value: postgres123 }
                                - { name: POSTGRES_DB, value: app }
                                - { name: PGDATA, value: /var/lib/postgresql/data/pgdata }
                              volumeMounts:
                                - { name: data, mountPath: /var/lib/postgresql/data }
                              resources:
                                requests: { cpu: "200m", memory: "256Mi" }
                                limits: { cpu: "500m", memory: "512Mi" }
                          volumes:
                            - name: data
                              persistentVolumeClaim:
                                claimName: ""
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-namespace"]
                toFieldPath: spec.forProvider.manifest.metadata.namespace
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-name"]
                toFieldPath: spec.forProvider.manifest.metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string: { type: Format, fmt: "%s-deploy" }
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-name"]
                toFieldPath: spec.forProvider.manifest.spec.selector.matchLabels["app.kubernetes.io/instance"]
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-name"]
                toFieldPath: spec.forProvider.manifest.spec.template.metadata.labels["app.kubernetes.io/instance"]
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-name"]
                toFieldPath: spec.forProvider.manifest.spec.template.spec.volumes[0].persistentVolumeClaim.claimName
                transforms:
                  - type: string
                    string: { type: Format, fmt: "%s-data" }
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.version
                toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].image
                transforms:
                  - type: string
                    string: { type: Format, fmt: "postgres:%s" }

          # Service
          - name: service
            base:
              apiVersion: kubernetes.crossplane.io/v1alpha2
              kind: Object
              spec:
                forProvider:
                  manifest:
                    apiVersion: v1
                    kind: Service
                    metadata:
                      labels:
                        app.kubernetes.io/component: database
                        app.kubernetes.io/managed-by: crossplane
                    spec:
                      type: ClusterIP
                      ports: [{ port: 5432, targetPort: 5432 }]
                      selector:
                        app.kubernetes.io/component: database
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-namespace"]
                toFieldPath: spec.forProvider.manifest.metadata.namespace
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-name"]
                toFieldPath: spec.forProvider.manifest.metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string: { type: Format, fmt: "%s-svc" }
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-name"]
                toFieldPath: spec.forProvider.manifest.spec.selector["app.kubernetes.io/instance"]
