---
# Redis Composition - Building Block
# Creates: PVC, ConfigMap, Deployment, Service, Secret (credentials)
# Deploys into the claim's namespace
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: redis
  labels:
    crossplane.io/xrd: redis.platform.chrishouse.io
spec:
  compositeTypeRef:
    apiVersion: platform.chrishouse.io/v1alpha1
    kind: Redis
  writeConnectionSecretsToNamespace: crossplane-system
  mode: Pipeline
  pipeline:
    - step: redis-resources
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- $xr := .observed.composite.resource }}
            {{- $ns := index $xr.metadata.labels "crossplane.io/claim-namespace" }}
            {{- $name := index $xr.metadata.labels "crossplane.io/claim-name" }}
            {{- $p := $xr.spec.parameters }}
            {{- $version := default "7.2" $p.version }}
            {{- $memoryMB := default 256 $p.memoryLimitMB }}
            {{- $storageGB := default 1 $p.storageGB }}
            {{- $policy := default "allkeys-lru" $p.maxMemoryPolicy }}
            ---
            # PVC
            apiVersion: kubernetes.crossplane.io/v1alpha2
            kind: Object
            metadata:
              name: {{ $xr.metadata.name }}-pvc
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: pvc
            spec:
              forProvider:
                manifest:
                  apiVersion: v1
                  kind: PersistentVolumeClaim
                  metadata:
                    name: {{ $name }}-data
                    namespace: {{ $ns }}
                    labels:
                      app.kubernetes.io/component: redis
                      app.kubernetes.io/managed-by: crossplane
                  spec:
                    accessModes: [ReadWriteOnce]
                    storageClassName: managed-csi
                    resources:
                      requests:
                        storage: {{ $storageGB }}Gi
            ---
            # ConfigMap
            apiVersion: kubernetes.crossplane.io/v1alpha2
            kind: Object
            metadata:
              name: {{ $xr.metadata.name }}-config
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: config
            spec:
              forProvider:
                manifest:
                  apiVersion: v1
                  kind: ConfigMap
                  metadata:
                    name: {{ $name }}-config
                    namespace: {{ $ns }}
                    labels:
                      app.kubernetes.io/component: redis
                      app.kubernetes.io/managed-by: crossplane
                  data:
                    redis.conf: |
                      appendonly yes
                      appendfsync everysec
                      save 900 1
                      save 300 10
                      save 60 10000
                      maxmemory {{ $memoryMB }}mb
                      maxmemory-policy {{ $policy }}
            ---
            # Deployment
            apiVersion: kubernetes.crossplane.io/v1alpha2
            kind: Object
            metadata:
              name: {{ $xr.metadata.name }}-deploy
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: deployment
            spec:
              forProvider:
                manifest:
                  apiVersion: apps/v1
                  kind: Deployment
                  metadata:
                    name: {{ $name }}
                    namespace: {{ $ns }}
                    labels:
                      app.kubernetes.io/component: redis
                      app.kubernetes.io/managed-by: crossplane
                  spec:
                    replicas: 1
                    strategy:
                      type: Recreate
                    selector:
                      matchLabels:
                        app.kubernetes.io/component: redis
                        app.kubernetes.io/instance: {{ $name }}
                    template:
                      metadata:
                        labels:
                          app.kubernetes.io/component: redis
                          app.kubernetes.io/instance: {{ $name }}
                      spec:
                        containers:
                          - name: redis
                            image: redis:{{ $version }}-alpine
                            command: [redis-server, /etc/redis/redis.conf]
                            ports: [{ containerPort: 6379 }]
                            volumeMounts:
                              - { name: data, mountPath: /data }
                              - { name: config, mountPath: /etc/redis }
                            resources:
                              requests: { cpu: "100m", memory: "128Mi" }
                              limits: { cpu: "500m", memory: "{{ $memoryMB }}Mi" }
                            readinessProbe:
                              tcpSocket: { port: 6379 }
                              initialDelaySeconds: 5
                            livenessProbe:
                              tcpSocket: { port: 6379 }
                              initialDelaySeconds: 15
                        volumes:
                          - name: data
                            persistentVolumeClaim:
                              claimName: {{ $name }}-data
                          - name: config
                            configMap:
                              name: {{ $name }}-config
            ---
            # Service
            apiVersion: kubernetes.crossplane.io/v1alpha2
            kind: Object
            metadata:
              name: {{ $xr.metadata.name }}-svc
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: service
            spec:
              forProvider:
                manifest:
                  apiVersion: v1
                  kind: Service
                  metadata:
                    name: {{ $name }}
                    namespace: {{ $ns }}
                    labels:
                      app.kubernetes.io/component: redis
                      app.kubernetes.io/managed-by: crossplane
                  spec:
                    type: ClusterIP
                    ports: [{ port: 6379, targetPort: 6379 }]
                    selector:
                      app.kubernetes.io/component: redis
                      app.kubernetes.io/instance: {{ $name }}
            ---
            # Credentials Secret
            apiVersion: kubernetes.crossplane.io/v1alpha2
            kind: Object
            metadata:
              name: {{ $xr.metadata.name }}-secret
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: secret
            spec:
              forProvider:
                manifest:
                  apiVersion: v1
                  kind: Secret
                  metadata:
                    name: {{ $name }}-credentials
                    namespace: {{ $ns }}
                    labels:
                      app.kubernetes.io/component: redis
                      app.kubernetes.io/managed-by: crossplane
                  stringData:
                    host: {{ $name }}
                    port: "6379"
                    url: "redis://{{ $name }}:6379"
