---
# Redis XRD (CompositeResourceDefinition)
# Defines a single-node Redis instance running in Kubernetes with PVC
# This is the "API" that platform consumers use to request Redis
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: redis.platform.chrishouse.io
spec:
  group: platform.chrishouse.io
  names:
    kind: Redis
    plural: redis
    shortNames:
      - rd
  claimNames:
    kind: RedisClaim
    plural: redisclaims
  connectionSecretKeys:
    - endpoint
    - host
    - port
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - parameters
              properties:
                parameters:
                  type: object
                  required:
                    - name
                    - environment
                    - storageGB
                  properties:
                    name:
                      type: string
                      description: "Redis instance name (used in resource naming)"
                      pattern: "^[a-z][a-z0-9-]{1,20}$"
                    environment:
                      type: string
                      description: "Environment name (dev, staging, prod)"
                      enum:
                        - dev
                        - staging
                        - prod
                    storageGB:
                      type: integer
                      description: "Storage size in GB for Redis persistence"
                      minimum: 1
                      maximum: 100
                      default: 1
                    redisVersion:
                      type: string
                      description: "Redis version"
                      enum:
                        - "7.2"
                        - "7.0"
                        - "6.2"
                      default: "7.2"
                    maxMemoryPolicy:
                      type: string
                      description: "Policy for evicting keys when max memory is reached"
                      enum:
                        - allkeys-lru
                        - volatile-lru
                        - allkeys-lfu
                        - volatile-lfu
                        - allkeys-random
                        - volatile-random
                        - noeviction
                      default: allkeys-lru
                    memoryLimitMB:
                      type: integer
                      description: "Memory limit in MB"
                      enum:
                        - 128
                        - 256
                        - 512
                        - 1024
                        - 2048
                      default: 256
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: "Current phase of the Redis instance"
                endpoint:
                  type: string
                  description: "Redis connection endpoint (host:port)"
                serviceName:
                  type: string
                  description: "Kubernetes service name"
                namespace:
                  type: string
                  description: "Kubernetes namespace"
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
      additionalPrinterColumns:
        - name: Name
          type: string
          jsonPath: ".spec.parameters.name"
        - name: Environment
          type: string
          jsonPath: ".spec.parameters.environment"
        - name: Version
          type: string
          jsonPath: ".spec.parameters.redisVersion"
        - name: Ready
          type: string
          jsonPath: ".status.conditions[?(@.type=='Ready')].status"
        - name: Age
          type: date
          jsonPath: ".metadata.creationTimestamp"
