apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: nodejs-goldenpath
  title: 🥚 Golden Path - Node.js Microservice
  description: Deploy a Node.js microservice to dev AND production clusters. Includes automatic promotion infrastructure.
  tags:
    - nodejs
    - quickstart
    - recommended
    - golden-path
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Service Details
      required:
        - service_name
        - team
        - description
      properties:
        service_name:
          title: Service Name
          type: string
          description: What should we call your service? (lowercase-with-dashes)
          pattern: '^[a-z][a-z0-9-]*$'
          ui:autofocus: true
          ui:help: 'Examples: user-api, payment-service, notification-worker'

        team:
          title: Team
          type: string
          description: Which team owns this service?
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group

        description:
          title: Description
          type: string
          description: What does this service do? (one sentence)
          ui:help: 'Example: Handles user authentication and authorization'

    - title: Production Configuration
      properties:
        includeProduction:
          title: Include Production Infrastructure
          type: boolean
          default: true
          description: Create production ArgoCD app, namespace, and ingress routes

        prodReplicas:
          title: Production Replicas
          type: integer
          description: Number of pods in production (min 2 for HA)
          default: 3
          minimum: 2
          maximum: 10

        enableHPA:
          title: Enable Horizontal Pod Autoscaling
          type: boolean
          default: true
          description: Automatically scale pods based on CPU usage

        maxReplicas:
          title: Maximum Replicas (for HPA)
          type: integer
          default: 10
          minimum: 3
          maximum: 50

      dependencies:
        prodReplicas:
          - includeProduction
        enableHPA:
          - includeProduction
        maxReplicas:
          - includeProduction

  steps:
    # Step 1: Scaffold application from template
    - id: fetch-template
      name: Scaffold Application
      action: fetch:template
      input:
        url: ./skeleton
        values:
          serviceName: ${{ parameters.service_name }}
          team: ${{ parameters.team | parseEntityRef | pick('name') }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.team }}
          repoUrl: github.com?owner=crh225&repo=${{ parameters.service_name }}
          namespace: ${{ parameters.team | parseEntityRef | pick('name') }}-dev

    # Step 2: Create and configure GitHub repository
    - id: publish-github
      name: Create GitHub Repository
      action: publish:github
      input:
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=crh225&repo=${{ parameters.service_name }}
        repoVisibility: public
        defaultBranch: main
        protectDefaultBranch: false

    - id: configure-repo
      name: Configure Repository
      action: armportal:github:configure-repo
      input:
        repoUrl: github.com?owner=crh225&repo=${{ parameters.service_name }}

    # Step 3: Create GitOps configuration (dev + prod manifests)
    - id: create-gitops-dev
      name: Create GitOps Configuration
      action: fetch:template
      input:
        url: ./gitops-manifests-dev
        targetPath: ./gitops/quickstart-services/${{ parameters.service_name }}
        values:
          serviceName: ${{ parameters.service_name }}
          team: ${{ parameters.team | parseEntityRef | pick('name') }}
          description: ${{ parameters.description }}
          repoUrl: https://github.com/crh225/${{ parameters.service_name }}
          devNamespace: ${{ parameters.team | parseEntityRef | pick('name') }}-dev
          devCluster: shared-dev-cluster

    - id: create-gitops-prod
      if: ${{ parameters.includeProduction }}
      action: fetch:template
      input:
        url: ./gitops-manifests-prod
        targetPath: ./gitops/quickstart-services/${{ parameters.service_name }}
        values:
          serviceName: ${{ parameters.service_name }}
          team: ${{ parameters.team | parseEntityRef | pick('name') }}
          description: ${{ parameters.description }}
          repoUrl: https://github.com/crh225/${{ parameters.service_name }}
          prodNamespace: ${{ parameters.team | parseEntityRef | pick('name') }}-prod
          prodClusterArgoCD: aks-app-spoke
          prodClusterCrossplane: app-spoke
          prodReplicas: ${{ parameters.prodReplicas }}
          enableHPA: ${{ parameters.enableHPA }}
          maxReplicas: ${{ parameters.maxReplicas }}

    # Step 4: Create ingress routes (fetches existing config, adds VirtualServices)
    - id: fetch-existing-istio
      name: Create Ingress Routes
      action: fetch:plain
      input:
        url: https://github.com/crh225/ARMServicePortal/tree/main/infra/kubernetes
        targetPath: ./gitops/kubernetes

    - id: create-hub-vs-dev
      action: fetch:template
      input:
        url: ./hub-virtualservice-dev
        targetPath: ./gitops/kubernetes/istio-hub
        values:
          serviceName: ${{ parameters.service_name }}
          team: ${{ parameters.team | parseEntityRef | pick('name') }}

    - id: append-hub-kustomize-dev
      action: roadiehq:utils:fs:append
      input:
        path: ./gitops/kubernetes/istio-hub/kustomization.yaml
        content: "\n  - virtualservice-${{ parameters.service_name }}-dev.yaml"

    - id: create-hub-vs
      if: ${{ parameters.includeProduction }}
      action: fetch:template
      input:
        url: ./hub-virtualservice
        targetPath: ./gitops/kubernetes/istio-hub
        values:
          serviceName: ${{ parameters.service_name }}
          team: ${{ parameters.team | parseEntityRef | pick('name') }}

    - id: create-spoke-vs
      if: ${{ parameters.includeProduction }}
      action: fetch:template
      input:
        url: ./spoke-virtualservice
        targetPath: ./gitops/kubernetes/istio-spoke
        values:
          serviceName: ${{ parameters.service_name }}
          team: ${{ parameters.team | parseEntityRef | pick('name') }}
          namespace: ${{ parameters.team | parseEntityRef | pick('name') }}-prod

    - id: append-hub-kustomize
      if: ${{ parameters.includeProduction }}
      action: roadiehq:utils:fs:append
      input:
        path: ./gitops/kubernetes/istio-hub/kustomization.yaml
        content: "  - virtualservice-${{ parameters.service_name }}-prod.yaml"

    - id: append-spoke-kustomize
      if: ${{ parameters.includeProduction }}
      action: roadiehq:utils:fs:append
      input:
        path: ./gitops/kubernetes/istio-spoke/kustomization.yaml
        content: "  - virtualservice-${{ parameters.service_name }}-prod.yaml"

    # Step 5: Submit GitOps pull request
    - id: publish-gitops-dev-only
      name: Submit GitOps PR
      if: ${{ not parameters.includeProduction }}
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=crh225&repo=ARMServicePortal
        branchName: service/${{ parameters.service_name }}
        title: 'feat: Add ${{ parameters.service_name }} to dev cluster'
        description: |
          ## New Service: ${{ parameters.service_name }}

          **Team:** ${{ parameters.team }}
          **Description:** ${{ parameters.description }}

          ---

          ### Development Environment

          | Field | Value |
          |-------|-------|
          | **Cluster** | shared-dev-cluster |
          | **Namespace** | ${{ parameters.team }}-dev |
          | **Trigger** | Push to main |
          | **Image Tag** | `latest` |

          ---

          ### This PR adds:

          - NamespaceClaim for dev namespace (${{ parameters.team }}-dev)
          - ArgoCD Application for dev (tracks `latest` tag)

          ---
          Generated by Backstage Golden Path Template
        sourcePath: ./gitops
        targetPath: infra

    - id: publish-gitops
      name: Submit GitOps PR
      if: ${{ parameters.includeProduction }}
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=crh225&repo=ARMServicePortal
        branchName: service/${{ parameters.service_name }}
        title: 'feat: Add ${{ parameters.service_name }} (dev + production)'
        description: |
          ## New Service: ${{ parameters.service_name }}

          **Team:** ${{ parameters.team }}
          **Description:** ${{ parameters.description }}

          ---

          ### Development Environment

          | Field | Value |
          |-------|-------|
          | **Cluster** | shared-dev-cluster |
          | **Namespace** | ${{ parameters.team }}-dev |
          | **Trigger** | Push to main |
          | **Image Tag** | `latest` |

          ---

          ### Production Environment

          | Field | Value |
          |-------|-------|
          | **Cluster** | aks-app-spoke |
          | **Namespace** | ${{ parameters.team }}-prod |
          | **Trigger** | GitHub Release (v*) |
          | **Replicas** | ${{ parameters.prodReplicas }} |
          | **HPA Enabled** | ${{ parameters.enableHPA }} |
          | **Production URL** | https://${{ parameters.service_name }}-prod.chrishouse.io |

          ---

          ### This PR adds:

          - NamespaceClaim for dev namespace (${{ parameters.team }}-dev)
          - NamespaceClaim for prod namespace (${{ parameters.team }}-prod)
          - ArgoCD Application for dev (tracks `latest` tag)
          - ArgoCD Application for prod (tracks semver tags)
          - Hub VirtualService (routes traffic to spoke)
          - Spoke VirtualService (routes traffic to service)

          ---

          ### Release Flow

          **Development:** Push to main → CI builds `latest` → ArgoCD deploys to dev

          **Production:** Create GitHub Release (e.g., v1.0.0) → CI builds versioned image → ArgoCD deploys to prod

          ---
          Generated by Backstage Golden Path Template
        sourcePath: ./gitops
        targetPath: infra

    # Step 6: Register in Backstage catalog
    - id: register-catalog
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish-github'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish-github'].output.remoteUrl }}
      - title: View in Catalog
        icon: catalog
        entityRef: ${{ steps['register-catalog'].output.entityRef }}
    text:
      - title: Next Steps
        content: |
          ## Service Created: ${{ parameters.service_name }}

          ✅ Repository created
          ✅ GitOps PR submitted - check the PR link above

          ---

          ### After PR Merge

          **Development deploys automatically** on every push to main.

          **Production** (if enabled): Create a GitHub Release with tag v1.0.0 to deploy.

          ---

          **Estimated deployment time:** 2-3 minutes after PR merge
