apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: nodejs-goldenpath
  title: Golden Path - Node.js Microservice
  description: Get started fast! Deploy a Node.js microservice to the shared dev cluster in under 5 minutes with just 3 fields.
  annotations:
    backstage.io/template-icon: 🥚
  tags:
    - nodejs
    - quickstart
    - recommended
    - golden-path
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Service Details
      required:
        - service_name
        - team
        - description
      properties:
        service_name:
          title: Service Name
          type: string
          description: What should we call your service? (lowercase-with-dashes)
          pattern: '^[a-z][a-z0-9-]*$'
          ui:autofocus: true
          ui:help: 'Examples: user-api, payment-service, notification-worker'

        team:
          title: Team
          type: string
          description: Which team owns this service?
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group

        description:
          title: Description
          type: string
          description: What does this service do? (one sentence)
          ui:help: 'Example: Handles user authentication and authorization'

  steps:
    # Step 1: Generate repository from template
    - id: fetch-template
      name: Fetch Application Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          serviceName: ${{ parameters.service_name }}
          team: ${{ parameters.team }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.team }}
          repoUrl: github.com?owner=crh225&repo=${{ parameters.service_name }}
          namespace: ${{ parameters.team }}-dev

    # Step 2: Create GitHub repository
    - id: publish-github
      name: Publish to GitHub
      action: publish:github
      input:
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=crh225&repo=${{ parameters.service_name }}
        repoVisibility: public
        defaultBranch: main
        protectDefaultBranch: false

    # Step 3: Create GitOps manifests in infra repo
    - id: create-gitops-pr
      name: Create GitOps Configuration
      action: fetch:template
      input:
        url: ./gitops-manifests
        targetPath: ./gitops
        values:
          serviceName: ${{ parameters.service_name }}
          team: ${{ parameters.team }}
          description: ${{ parameters.description }}
          repoUrl: https://github.com/crh225/${{ parameters.service_name }}
          namespace: ${{ parameters.team }}-dev
          targetCluster: shared-dev-cluster

    # Step 4: Create pull request in ARMServicePortal repo
    - id: publish-gitops
      name: Submit GitOps PR
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=crh225&repo=ARMServicePortal
        branchName: service/${{ parameters.service_name }}
        title: 'feat: Add ${{ parameters.service_name }} to shared dev cluster'
        description: |
          ## New Service: ${{ parameters.service_name }}

          **Team:** ${{ parameters.team }}
          **Description:** ${{ parameters.description }}
          **Target Cluster:** shared-dev-cluster
          **Namespace:** ${{ parameters.team }}-dev

          This PR adds:
          - NamespaceClaim for team namespace isolation
          - ArgoCD Application pointing to https://github.com/crh225/${{ parameters.service_name }}

          Once merged, ArgoCD will automatically deploy the service.

          ---
          🤖 Generated by Backstage Quick Start Template
        sourcePath: ./gitops
        targetPath: infra/quickstart-services/${{ parameters.service_name }}

    # Step 5: Register in Backstage catalog
    - id: register-catalog
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish-github'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        icon: 🥚
        url: ${{ steps['publish-github'].output.remoteUrl }}
      - title: GitOps PR
        icon: 🥚
        url: ${{ steps['publish-gitops'].output.remoteUrl }}
      - title: View in Catalog
        icon: catalog
        entityRef: ${{ steps['register-catalog'].output.entityRef }}
    text:
      - title: Next Steps
        content: |
          ✅ Repository created: ${{ steps['publish-github'].output.remoteUrl }}
          ✅ GitOps PR submitted: ${{ steps['publish-gitops'].output.remoteUrl }}

          **What happens next:**
          1. Review and merge the GitOps PR
          2. ArgoCD will create your namespace on shared-dev-cluster
          3. ArgoCD will deploy your service automatically
          4. Your service will be available at: http://${{ parameters.service_name }}.shared-dev.internal

          **Estimated deployment time:** 2-3 minutes after PR merge
