# Team Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: team-pep
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: team-pep
    armportal.chrishouse.io/team: pep
    armportal.chrishouse.io/environment: dev
