apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: "fullstackapp-dev"
  title: fullstackapp (dev)
  description: "Full-stack application deployed via ARM Portal Building Blocks"
  labels:
    armportal.chrishouse.io/blueprint: "xp-building-blocks"
    armportal.chrishouse.io/environment: dev
    armportal.chrishouse.io/provider: crossplane
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/crh225/ARMServicePortal/blob/main/infra/crossplane/claims/fullstackapp-dev/claims.yaml"
    backstage.io/managed-by-origin-location: "url:https://github.com/crh225/ARMServicePortal/blob/main/infra/crossplane/claims/fullstackapp-dev/claims.yaml"
    armportal.chrishouse.io/request-id: "269"
    armportal.chrishouse.io/created-by: crh225
    armportal.chrishouse.io/provisioned-at: "2025-12-15T00:45:55.742Z"
  tags:
    - kubernetes
    - crossplane
    - dev
    - "building-blocks"
  links:
    - url: "https://github.com/crh225/ARMServicePortal/blob/main/infra/crossplane/claims/fullstackapp-dev/claims.yaml"
      title: Crossplane Claims
      icon: code
    - url: "https://github.com/crh225/ARMServicePortal/pull/269"
      title: Provisioning PR
      icon: github
spec:
  owner: "user:crh225"
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: "fullstackapp-cache-dev"
  title: fullstackapp Redis (dev)
  description: Redis component for fullstackapp
  labels:
    armportal.chrishouse.io/blueprint: "xp-building-blocks"
    armportal.chrishouse.io/component: redis
    armportal.chrishouse.io/environment: dev
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/crh225/ARMServicePortal/blob/main/infra/crossplane/claims/fullstackapp-dev/claims.yaml"
    backstage.io/managed-by-origin-location: "url:https://github.com/crh225/ARMServicePortal/blob/main/infra/crossplane/claims/fullstackapp-dev/claims.yaml"
    backstage.io/kubernetes-id: "fullstackapp-cache"
    backstage.io/kubernetes-namespace: "fullstackapp-dev"
  tags:
    - kubernetes
    - crossplane
    - dev
    - redis
spec:
  type: cache
  lifecycle: development
  owner: "user:crh225"
  system: "fullstackapp-dev"
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: "fullstackapp-mq-dev"
  title: fullstackapp RabbitMQ (dev)
  description: RabbitMQ component for fullstackapp
  labels:
    armportal.chrishouse.io/blueprint: "xp-building-blocks"
    armportal.chrishouse.io/component: rabbitmq
    armportal.chrishouse.io/environment: dev
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/crh225/ARMServicePortal/blob/main/infra/crossplane/claims/fullstackapp-dev/claims.yaml"
    backstage.io/managed-by-origin-location: "url:https://github.com/crh225/ARMServicePortal/blob/main/infra/crossplane/claims/fullstackapp-dev/claims.yaml"
    backstage.io/kubernetes-id: "fullstackapp-mq"
    backstage.io/kubernetes-namespace: "fullstackapp-dev"
  tags:
    - kubernetes
    - crossplane
    - dev
    - rabbitmq
spec:
  type: "message-queue"
  lifecycle: development
  owner: "user:crh225"
  system: "fullstackapp-dev"