apiVersion: platform.chrishouse.io/v1alpha1
kind: NamespaceClaim
metadata:
  name: red-dev-pr-1
  namespace: crossplane-system
  labels:
    team: red
    environment: preview
    pr-number: "1"
    ephemeral: "true"
    created-by: backstage
    service: pricing-api
  annotations:
    description: "Preview environment for PR #1"
    preview-url: "https://pricing-api-pr-1.red.chrishouse.io"
spec:
  parameters:
    targetCluster: shared-dev-cluster
    namespaceName: red-dev-pr-1
    enableResourceQuota: true
    enableNetworkPolicy: true
    enableLimitRange: true
    resourceQuota:
      requestsCpu: "1"
      requestsMemory: "2Gi"
      limitsCpu: "2"
      limitsMemory: "4Gi"
      pods: 10
    limitRange:
      cpuRequest: "100m"
      cpuLimit: "500m"
      memoryRequest: "128Mi"
      memoryLimit: "512Mi"
