# Conda environment for Azure ML training jobs

name: mhd-training
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - pandas>=2.0.0
    - numpy>=1.24.0
    - scikit-learn>=1.3.0
    - xgboost>=2.0.0
    - mlflow>=2.9.0
    - azureml-mlflow>=1.54.0
    - joblib>=1.3.0
