apiVersion: platform.chrishouse.io/v1alpha1
kind: NamespaceClaim
metadata:
  name: red-prod
  namespace: crossplane-system
  labels:
    team: red
    environment: prod
    created-by: backstage
    template: promote-to-production
  annotations:
    description: "Production namespace for red team"
    created-via: "backstage-promote-to-production-template"
    service: "pricing-api"
spec:
  parameters:
    targetCluster: aks-app-spoke
    namespaceName: red-prod
    labels:
      team: red
      environment: prod
      managed-by: crossplane
      backstage.io/kubernetes-id: red

    # Enable all isolation features
    enableResourceQuota: true
    enableNetworkPolicy: true
    enableLimitRange: true

    # Production quotas (higher limits than dev)
    resourceQuota:
      requestsCpu: "4"
      requestsMemory: "8Gi"
      limitsCpu: "8"
      limitsMemory: "16Gi"
      pods: 100

    # Default limits for individual containers
    limitRange:
      cpuRequest: "100m"
      cpuLimit: "1"
      memoryRequest: "128Mi"
      memoryLimit: "1Gi"
